[2025-04-07 11:03:00] Watching for file changes with StatReloader
[2025-04-07 11:04:11] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 11:04:12] Watching for file changes with StatReloader
[2025-04-07 11:04:39] Internal Server Error: /admin/new-resources-post/
Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\qiuqi\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 166, in admin_add_resources_post
    knowledge_resources = ResourceMetadata.objects.filter(is_template=True)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'is_template' into field. Choices are: commodities, created_at, created_by, created_by_id, description, event, id, information_system, is_approved, is_featured, map, media, news, policy, product, project, publication, resource_type, slug, tags, technology, title, training_seminar, updated_at, webinar
[2025-04-07 11:04:39] Not Found: /favicon.ico
[2025-04-07 11:05:36] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 11:05:37] Watching for file changes with StatReloader
[2025-04-07 11:05:42] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 11:05:43] Watching for file changes with StatReloader
[2025-04-07 11:09:01] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 11:09:02] Watching for file changes with StatReloader
[2025-04-07 11:09:33] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 11:09:34] Watching for file changes with StatReloader
[2025-04-07 11:09:49] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:09:49] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:19:30] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 11:19:31] Watching for file changes with StatReloader
[2025-04-07 11:19:46] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:19:46] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:20:45] Internal Server Error: /admin/new-resources-post/
Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.DataError: (1406, "Data too long for column 'resource_type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 203, in admin_add_resources_post
    metadata = ResourceMetadata.objects.create(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'resource_type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\qiuqi\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 263, in admin_add_resources_post
    return render(request, "pages/resources-post.html", context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 83, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\base\base.py", line 531, in validate_no_broken_transaction
    raise TransactionManagementError(
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
[2025-04-07 11:31:09] Internal Server Error: /admin/new-resources-post/
Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.DataError: (1406, "Data too long for column 'resource_type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 203, in admin_add_resources_post
    metadata = ResourceMetadata.objects.create(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'resource_type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\qiuqi\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 263, in admin_add_resources_post
    return render(request, "pages/resources-post.html", context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 83, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\base\base.py", line 531, in validate_no_broken_transaction
    raise TransactionManagementError(
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
[2025-04-07 11:32:14] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:32:14] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:32:25] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:32:25] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:32:47] Internal Server Error: /admin/new-resources-post/
Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.DataError: (1406, "Data too long for column 'resource_type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 203, in admin_add_resources_post
    metadata = ResourceMetadata.objects.create(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'resource_type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\qiuqi\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 263, in admin_add_resources_post
    return render(request, "pages/resources-post.html", context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\utils.py", line 83, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\db\backends\base\base.py", line 531, in validate_no_broken_transaction
    raise TransactionManagementError(
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
[2025-04-07 11:33:55] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\models.py changed, reloading.
[2025-04-07 11:33:56] Watching for file changes with StatReloader
[2025-04-07 11:34:12] Watching for file changes with StatReloader
[2025-04-07 11:35:48] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\models.py changed, reloading.
[2025-04-07 11:35:49] Watching for file changes with StatReloader
[2025-04-07 11:35:59] Watching for file changes with StatReloader
[2025-04-07 11:36:18] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 11:36:18] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 13:12:19] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 13:12:20] Watching for file changes with StatReloader
[2025-04-07 13:37:12] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 13:37:13] Watching for file changes with StatReloader
[2025-04-07 13:38:04] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 13:38:04] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 13:39:25] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 13:39:26] Watching for file changes with StatReloader
[2025-04-07 13:40:13] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 13:40:14] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 13:41:21] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 13:41:22] Watching for file changes with StatReloader
[2025-04-07 13:44:22] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 13:44:22] Not Found: /sourceMap/assets/css/shadow.css.map
[2025-04-07 13:48:52] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 13:48:53] Watching for file changes with StatReloader
[2025-04-07 13:49:16] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 13:49:17] Watching for file changes with StatReloader
[2025-04-07 13:57:47] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 13:57:48] Watching for file changes with StatReloader
[2025-04-07 14:23:33] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 14:23:34] Watching for file changes with StatReloader
[2025-04-07 14:27:27] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 14:27:28] Watching for file changes with StatReloader
[2025-04-07 14:44:47] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 14:44:48] Watching for file changes with StatReloader
[2025-04-07 14:44:50] Internal Server Error: /admin/resources-post/
Traceback (most recent call last):
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\qiuqi\Desktop\km-system-v2\km-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py", line 92, in admin_resources_post
    paginator = Paginator(resources, 10)  # Show 10 resources per page
UnboundLocalError: local variable 'resources' referenced before assignment
[2025-04-07 14:44:51] Not Found: /favicon.ico
[2025-04-07 14:45:37] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 14:45:38] Watching for file changes with StatReloader
[2025-04-07 14:45:59] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 14:46:00] Watching for file changes with StatReloader
[2025-04-07 14:47:13] C:\Users\qiuqi\Desktop\km-system-v2\kmhub\appAdmin\views\resources_post_view.py changed, reloading.
[2025-04-07 14:47:14] Watching for file changes with StatReloader
[2025-04-08 10:24:56] Watching for file changes with StatReloader
[2025-04-08 10:25:30] Watching for file changes with StatReloader
[2025-04-08 10:25:35] Not Found: /favicon.ico
